apiVersion: apps/v1
kind: Deployment
metadata:
  name: spot-backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spot-backend
  template:
    metadata:
      labels:
        app: spot-backend
    spec:
      containers:
        - name: spot-backend
          image: __IMAGE__
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: TZ
              value: Asia/Seoul
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
      imagePullSecrets:
        - name: ncp-registry-secret
