name: Stg Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle
        uses: actions/cache@v4.2.3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: gradle-

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: move jar file to deploy
        run: mv ./build/libs/*.jar ./deploy

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to NCP Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ secrets.NCP_CONTAINER_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          context: ./deploy
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.NCP_CONTAINER_REGISTRY }}/spot-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Set IMAGE variable
        run: echo "IMAGE=${{ secrets.NCP_CONTAINER_REGISTRY }}/spot-backend:${{ github.sha }}" >> $GITHUB_ENV

      - name: Substitute image tag in deployment.yaml
        run: |
          sed -i "s|__IMAGE__|${IMAGE}|g" deploy/stg/spot-backend-deployment.yaml

      - name: Copy deployment.yaml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          source: deploy/stg/
          target: /home/ubuntu/deploy/stg
          strip_components: 2

      - name: Deploy to K3s via kubectl
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            kubectl apply -f /home/ubuntu/deploy/stg/
